apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: more-cars-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: more-cars
      port: 443
      protocol: HTTPS
      hostname: "*.more-cars.internal"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: certificate-more-cars-wildcard
