apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: more-cars-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: more-cars
      port: 443
      protocol: HTTPS
      hostname: "*.default.fast-cars.info"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: certificate-more-cars-wildcard
